# Generated by Django 3.0 on 2020-05-24 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaths', models.IntegerField(default=0)),
                ('hospitalizations', models.IntegerField(default=0)),
                ('totalTests', models.IntegerField(default=0)),
                ('dateEntry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.DateEntry')),
            ],
        ),
    ]
