# Generated by Django 3.0 on 2020-05-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_otherstats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherStats',
            new_name='Detail',
        ),
    ]
