# Generated by Django 3.0 on 2020-05-24 22:14

from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200523_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[(tracker.models.LocationType['N'], 'NATION'), (tracker.models.LocationType['S'], 'STATE'), (tracker.models.LocationType['C'], 'COUNTY')], default=tracker.models.LocationType['N'], max_length=5),
        ),
    ]
