# Generated by Django 3.0 on 2020-05-28 01:21

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[(tracker.models.LocationType['N'], 'NATION'), (tracker.models.LocationType['S'], 'STATE'), (tracker.models.LocationType['C'], 'COUNTY')], default=tracker.models.LocationType['N'], max_length=6),
        ),
    ]
