# Generated by Django 3.0 on 2020-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200527_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateentry',
            options={'ordering': ['date'], 'verbose_name_plural': 'date_entries'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='detail',
            name='newTests',
            field=models.IntegerField(default=0),
        ),
    ]
