# Generated by Django 3.0 on 2020-06-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200601_1940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dateentry',
            unique_together={('date', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('type', 'name')},
        ),
    ]
